plugins { id 'com.android.application' }

android {
    namespace 'com.txmusic.player'
    compileSdk 35

    defaultConfig {
        applicationId 'com.txmusic.player'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '4.1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
